### ISSUE TITLE
Please add scph-5000  .  Thank you!

### ISSUE THREAD

**Issue by Nonstopxiaowei** [jdfr228/PS1-Disc-Based-Game-ID#3]
Please add scph-5000  .  Thank you!

**Comment by jdfr228** [comment]
I have added a patch for SCPH-5000 based on a dump from planetemu, since PSXDEV indicated their 5000 BIOS dump was bad.  Be sure to check your CRC32 to make sure you have the right version before patching.  Updated zip is in the Releases section as 0.91 or you can get just the one xdelta from the patches folder.

Looked for SCPH-5001 as well which Wikipedia and other sources list as an NTSC-U version of the same model, but it doesn't seem to actually exist.

Also please let me know if you try the flashing program as current testers have been having issues getting it to detect their flash chip and write to it.  External flashing with other hardware is definitely recommended for now.
